INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_ORCA_BLOCKS ORCA_BLOCKS)

FIND_PATH(
    ORCA_BLOCKS_INCLUDE_DIRS
    NAMES ORCA_BLOCKS/api.h
    HINTS $ENV{ORCA_BLOCKS_DIR}/include
        ${PC_ORCA_BLOCKS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    ORCA_BLOCKS_LIBRARIES
    NAMES gnuradio-ORCA_BLOCKS
    HINTS $ENV{ORCA_BLOCKS_DIR}/lib
        ${PC_ORCA_BLOCKS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ORCA_BLOCKS DEFAULT_MSG ORCA_BLOCKS_LIBRARIES ORCA_BLOCKS_INCLUDE_DIRS)
MARK_AS_ADVANCED(ORCA_BLOCKS_LIBRARIES ORCA_BLOCKS_INCLUDE_DIRS)

