-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity CFOEcordic_atan_vbkb_rom is 
    generic(
             dwidth     : integer := 22; 
             awidth     : integer := 5; 
             mem_size    : integer := 22
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of CFOEcordic_atan_vbkb_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 => "1100100100001111110111", 1 => "0111011010110001100111", 
    2 => "0011111010110110111011", 3 => "0001111111010101101111", 
    4 => "0000111111111010101011", 5 => "0000011111111111010101", 
    6 => "0000001111111111111011", 7 => "0000000111111111111111", 
    8 => "0000000100000000000000", 9 => "0000000010000000000000", 
    10 => "0000000001000000000000", 11 => "0000000000100000000000", 
    12 => "0000000000010000000000", 13 => "0000000000001000000000", 
    14 => "0000000000000100000000", 15 => "0000000000000010000000", 
    16 => "0000000000000001000000", 17 => "0000000000000000100000", 
    18 => "0000000000000000010000", 19 => "0000000000000000001000", 
    20 => "0000000000000000000100", 21 => "0000000000000000000010" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity CFOEcordic_atan_vbkb is
    generic (
        DataWidth : INTEGER := 22;
        AddressRange : INTEGER := 22;
        AddressWidth : INTEGER := 5);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of CFOEcordic_atan_vbkb is
    component CFOEcordic_atan_vbkb_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    CFOEcordic_atan_vbkb_rom_U :  component CFOEcordic_atan_vbkb_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


